// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fecwtquqfbgpawkmxzvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlY3d0cXVxZmJncGF3a214enZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDUyNjUsImV4cCI6MjA3NDIyMTI2NX0.xixQal5K_87D-fpOnLz1Fqx3kZUGeL3mbSZ2LH8gT-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});